# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Problemas/io_basico.xdc

# Block Designs: bd/microblazer_aula6/microblazer_aula6.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_aula6 || ORIG_REF_NAME==microblazer_aula6}]

# IP: bd/microblazer_aula6/ip/microblazer_aula6_microblaze_0_0/microblazer_aula6_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_aula6_microblaze_0_0 || ORIG_REF_NAME==microblazer_aula6_microblaze_0_0}]

# IP: bd/microblazer_aula6/ip/microblazer_aula6_dlmb_v10_0/microblazer_aula6_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_aula6_dlmb_v10_0 || ORIG_REF_NAME==microblazer_aula6_dlmb_v10_0}]

# IP: bd/microblazer_aula6/ip/microblazer_aula6_ilmb_v10_0/microblazer_aula6_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_aula6_ilmb_v10_0 || ORIG_REF_NAME==microblazer_aula6_ilmb_v10_0}]

# IP: bd/microblazer_aula6/ip/microblazer_aula6_dlmb_bram_if_cntlr_0/microblazer_aula6_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_aula6_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==microblazer_aula6_dlmb_bram_if_cntlr_0}]

# IP: bd/microblazer_aula6/ip/microblazer_aula6_ilmb_bram_if_cntlr_0/microblazer_aula6_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_aula6_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==microblazer_aula6_ilmb_bram_if_cntlr_0}]

# IP: bd/microblazer_aula6/ip/microblazer_aula6_lmb_bram_0/microblazer_aula6_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_aula6_lmb_bram_0 || ORIG_REF_NAME==microblazer_aula6_lmb_bram_0}]

# IP: bd/microblazer_aula6/ip/microblazer_aula6_microblaze_0_axi_periph_0/microblazer_aula6_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_aula6_microblaze_0_axi_periph_0 || ORIG_REF_NAME==microblazer_aula6_microblaze_0_axi_periph_0}]

# IP: bd/microblazer_aula6/ip/microblazer_aula6_mdm_1_0/microblazer_aula6_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_aula6_mdm_1_0 || ORIG_REF_NAME==microblazer_aula6_mdm_1_0}]

# IP: bd/microblazer_aula6/ip/microblazer_aula6_clk_wiz_1_0/microblazer_aula6_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_aula6_clk_wiz_1_0 || ORIG_REF_NAME==microblazer_aula6_clk_wiz_1_0}]

# IP: bd/microblazer_aula6/ip/microblazer_aula6_rst_clk_wiz_1_100M_0/microblazer_aula6_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_aula6_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==microblazer_aula6_rst_clk_wiz_1_100M_0}]

# IP: bd/microblazer_aula6/ip/microblazer_aula6_axi_gpio_0_0/microblazer_aula6_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_aula6_axi_gpio_0_0 || ORIG_REF_NAME==microblazer_aula6_axi_gpio_0_0}]

# IP: bd/microblazer_aula6/ip/microblazer_aula6_axi_gpio_0_1/microblazer_aula6_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_aula6_axi_gpio_0_1 || ORIG_REF_NAME==microblazer_aula6_axi_gpio_0_1}]

# IP: bd/microblazer_aula6/ip/microblazer_aula6_xbar_0/microblazer_aula6_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_aula6_xbar_0 || ORIG_REF_NAME==microblazer_aula6_xbar_0}]

# XDC: bd/microblazer_aula6/ip/microblazer_aula6_microblaze_0_0/microblazer_aula6_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblazer_aula6_microblaze_0_0 || ORIG_REF_NAME==microblazer_aula6_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/microblazer_aula6/ip/microblazer_aula6_microblaze_0_0/microblazer_aula6_microblaze_0_0_ooc.xdc

# XDC: bd/microblazer_aula6/ip/microblazer_aula6_dlmb_v10_0/microblazer_aula6_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblazer_aula6_dlmb_v10_0 || ORIG_REF_NAME==microblazer_aula6_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/microblazer_aula6/ip/microblazer_aula6_dlmb_v10_0/microblazer_aula6_dlmb_v10_0_ooc.xdc

# XDC: bd/microblazer_aula6/ip/microblazer_aula6_ilmb_v10_0/microblazer_aula6_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblazer_aula6_ilmb_v10_0 || ORIG_REF_NAME==microblazer_aula6_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/microblazer_aula6/ip/microblazer_aula6_ilmb_v10_0/microblazer_aula6_ilmb_v10_0_ooc.xdc

# XDC: bd/microblazer_aula6/ip/microblazer_aula6_dlmb_bram_if_cntlr_0/microblazer_aula6_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/microblazer_aula6/ip/microblazer_aula6_ilmb_bram_if_cntlr_0/microblazer_aula6_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/microblazer_aula6/ip/microblazer_aula6_lmb_bram_0/microblazer_aula6_lmb_bram_0_ooc.xdc

# XDC: bd/microblazer_aula6/ip/microblazer_aula6_mdm_1_0/microblazer_aula6_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblazer_aula6_mdm_1_0 || ORIG_REF_NAME==microblazer_aula6_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/microblazer_aula6/ip/microblazer_aula6_mdm_1_0/microblazer_aula6_mdm_1_0_ooc.xdc

# XDC: bd/microblazer_aula6/ip/microblazer_aula6_clk_wiz_1_0/microblazer_aula6_clk_wiz_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblazer_aula6_clk_wiz_1_0 || ORIG_REF_NAME==microblazer_aula6_clk_wiz_1_0}] {/U0 }]/U0 ]]

# XDC: bd/microblazer_aula6/ip/microblazer_aula6_clk_wiz_1_0/microblazer_aula6_clk_wiz_1_0_ooc.xdc

# XDC: bd/microblazer_aula6/ip/microblazer_aula6_clk_wiz_1_0/microblazer_aula6_clk_wiz_1_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblazer_aula6_clk_wiz_1_0 || ORIG_REF_NAME==microblazer_aula6_clk_wiz_1_0}] {/U0 }]/U0 ]]

# XDC: bd/microblazer_aula6/ip/microblazer_aula6_rst_clk_wiz_1_100M_0/microblazer_aula6_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_aula6_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==microblazer_aula6_rst_clk_wiz_1_100M_0}]

# XDC: bd/microblazer_aula6/ip/microblazer_aula6_rst_clk_wiz_1_100M_0/microblazer_aula6_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/microblazer_aula6/ip/microblazer_aula6_rst_clk_wiz_1_100M_0/microblazer_aula6_rst_clk_wiz_1_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazer_aula6_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==microblazer_aula6_rst_clk_wiz_1_100M_0}]

# XDC: bd/microblazer_aula6/ip/microblazer_aula6_axi_gpio_0_0/microblazer_aula6_axi_gpio_0_0_ooc.xdc

# XDC: bd/microblazer_aula6/ip/microblazer_aula6_axi_gpio_0_0/microblazer_aula6_axi_gpio_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblazer_aula6_axi_gpio_0_0 || ORIG_REF_NAME==microblazer_aula6_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/microblazer_aula6/ip/microblazer_aula6_axi_gpio_0_0/microblazer_aula6_axi_gpio_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblazer_aula6_axi_gpio_0_0 || ORIG_REF_NAME==microblazer_aula6_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/microblazer_aula6/ip/microblazer_aula6_axi_gpio_0_1/microblazer_aula6_axi_gpio_0_1_ooc.xdc

# XDC: bd/microblazer_aula6/ip/microblazer_aula6_axi_gpio_0_1/microblazer_aula6_axi_gpio_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblazer_aula6_axi_gpio_0_1 || ORIG_REF_NAME==microblazer_aula6_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/microblazer_aula6/ip/microblazer_aula6_axi_gpio_0_1/microblazer_aula6_axi_gpio_0_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==microblazer_aula6_axi_gpio_0_1 || ORIG_REF_NAME==microblazer_aula6_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/microblazer_aula6/ip/microblazer_aula6_xbar_0/microblazer_aula6_xbar_0_ooc.xdc

# XDC: bd/microblazer_aula6/microblazer_aula6_ooc.xdc
