# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]

add_files T:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/bd/microblazer_aula6/microblazer_aula6.bd
set_property used_in_implementation false [get_files -all t:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/bd/microblazer_aula6/ip/microblazer_aula6_microblaze_0_0/microblazer_aula6_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all t:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/bd/microblazer_aula6/ip/microblazer_aula6_microblaze_0_0/microblazer_aula6_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/bd/microblazer_aula6/ip/microblazer_aula6_dlmb_v10_0/microblazer_aula6_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all t:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/bd/microblazer_aula6/ip/microblazer_aula6_dlmb_v10_0/microblazer_aula6_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/bd/microblazer_aula6/ip/microblazer_aula6_ilmb_v10_0/microblazer_aula6_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all t:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/bd/microblazer_aula6/ip/microblazer_aula6_ilmb_v10_0/microblazer_aula6_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/bd/microblazer_aula6/ip/microblazer_aula6_dlmb_bram_if_cntlr_0/microblazer_aula6_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/bd/microblazer_aula6/ip/microblazer_aula6_ilmb_bram_if_cntlr_0/microblazer_aula6_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/bd/microblazer_aula6/ip/microblazer_aula6_lmb_bram_0/microblazer_aula6_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/bd/microblazer_aula6/ip/microblazer_aula6_mdm_1_0/microblazer_aula6_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all t:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/bd/microblazer_aula6/ip/microblazer_aula6_mdm_1_0/microblazer_aula6_mdm_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/bd/microblazer_aula6/ip/microblazer_aula6_clk_wiz_1_0/microblazer_aula6_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all t:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/bd/microblazer_aula6/ip/microblazer_aula6_clk_wiz_1_0/microblazer_aula6_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/bd/microblazer_aula6/ip/microblazer_aula6_clk_wiz_1_0/microblazer_aula6_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all t:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/bd/microblazer_aula6/ip/microblazer_aula6_rst_clk_wiz_1_100M_0/microblazer_aula6_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all t:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/bd/microblazer_aula6/ip/microblazer_aula6_rst_clk_wiz_1_100M_0/microblazer_aula6_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/bd/microblazer_aula6/ip/microblazer_aula6_rst_clk_wiz_1_100M_0/microblazer_aula6_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all t:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/bd/microblazer_aula6/ip/microblazer_aula6_axi_gpio_0_0/microblazer_aula6_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/bd/microblazer_aula6/ip/microblazer_aula6_axi_gpio_0_0/microblazer_aula6_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all t:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/bd/microblazer_aula6/ip/microblazer_aula6_axi_gpio_0_0/microblazer_aula6_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all t:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/bd/microblazer_aula6/ip/microblazer_aula6_axi_gpio_0_1/microblazer_aula6_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/bd/microblazer_aula6/ip/microblazer_aula6_axi_gpio_0_1/microblazer_aula6_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all t:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/bd/microblazer_aula6/ip/microblazer_aula6_axi_gpio_0_1/microblazer_aula6_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all t:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/bd/microblazer_aula6/ip/microblazer_aula6_xbar_0/microblazer_aula6_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all T:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/bd/microblazer_aula6/microblazer_aula6_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files T:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/bd/microblazer_aula6/microblazer_aula6.bd]

read_vhdl -library xil_defaultlib T:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/sources_1/new/Toplevel.vhd
read_xdc T:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/constrs_1/imports/Problemas/io_basico.xdc
set_property used_in_implementation false [get_files T:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.srcs/constrs_1/imports/Problemas/io_basico.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir T:/###Lucas/Lucassoaexercicios/uc_basico/uc_basico.cache/wt [current_project]
set_property parent.project_dir T:/###Lucas/Lucassoaexercicios/uc_basico [current_project]
synth_design -top Toplevel -part xc7a100tcsg324-1
write_checkpoint Toplevel.dcp
report_utilization -file Toplevel_utilization_synth.rpt -pb Toplevel_utilization_synth.pb
